export const AuthTypes = {
	LOGIN: 'LOGIN',
	LOGIN_FAIL: 'LOGIN_FAIL',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGOUT: 'LOGOUT',
	GET_PROFILE: 'GET_PROFILE',
	GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',
	GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
	SET_IS_LOADING: 'SET_IS_LOADING_AUTH',
};

export const UserTypes = {
	CREATE: 'CREATE_USER',
	CREATE_FAIL: 'CREATE_USER_FAIL',
	CREATE_SUCCESS: 'CREATE_USER_SUCCESS',
	SET_IS_LOADING: 'SET_IS_LOADING_USER',
	CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION_USER',
};
